<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <title>User Dashboard</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Venue and Retreat Booking - Tripavie" />
    <meta name="keywords" content="Travel, Yoga, Venue, Retreat" />
    <meta name="author" content="DepressedPsychiatrist" />
    <meta name="email" content="info@tripavie.com" />
    <meta name="website" content="https://tripavie.com/" />
    <!-- favicon -->
    <link rel="shortcut icon" href="{{asset('favicon.png')}}">
    <!-- Bootstrap -->
    <link href="{{asset('assets/user/dashboard/css/bootstrap.min.css')}}" rel="stylesheet" type="text/css" />
    <!-- simplebar -->
    <link href="{{asset('assets/user/dashboard/css/simplebar.css')}}" rel="stylesheet" type="text/css" />

    <!-- Icons -->
    <link href="{{asset('assets/user/dashboard/css/materialdesignicons.min.css')}}" rel="stylesheet" type="text/css" />
    <link href="{{asset('assets/user/dashboard/css/tabler-icons.min.css')}}" rel="stylesheet" type="text/css" />
    <link href="{{asset('assets/user/dashboard/css/line.css')}}" rel="stylesheet">
    <!-- Css -->
    <link href="{{asset('assets/user/dashboard/css/style.min.css')}}" rel="stylesheet" type="text/css" id="theme-opt" />

    <!-- CSS generated by mix -->
    <link href="{{asset('assets/user/dashboard/css/app.css')}}" rel="stylesheet">
</head>

<body>
    <div id="app">
        <home-app>

        </home-app>
    </div>
    <!-- javascript -->
    <!-- Generated by mix -->
    <script src="{{asset('assets/user/dashboard/js/app.js')}}"></script>

    <script src="{{asset('assets/user/dashboard/js/bootstrap.bundle.min.js')}}"></script>
    <!-- simplebar -->
    <script src="{{asset('assets/user/dashboard/js/simplebar.min.js')}}"></script>
    <!-- Icons -->
    <script src="{{asset('assets/user/dashboard/js/feather.min.js')}}"></script>
    <!-- Main Js -->
    <script src="{{asset('assets/user/dashboard/js/plugins.init.js')}}"></script>
    <!-- initially called app.js, renamed to main.js because app.js will be generated by mix -->
    <script src="{{asset('assets/user/dashboard/js/main.js')}}"></script>

</body>

</html>
