<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <title>Tripavie Admin</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="A fully featured admin theme which can be used to build CRM, CMS, etc." name="description" />
    <meta content="Coderthemes" name="author" />
    <!-- favicon -->
    <link rel="shortcut icon" href="{{asset('favicon.png')}}">

    <!-- third party css -->
    <link href="{{asset('assets/admin/css/vendor/jquery-jvectormap-1.2.2.css')}}" rel="stylesheet" type="text/css" />
    <!-- third party css end -->

    <!-- App css -->
    <link href="{{asset('assets/admin/css/icons.min.css')}}" rel="stylesheet" type="text/css" />
    <link href="{{asset('assets/admin/css/app-creative.min.css')}}" rel="stylesheet" type="text/css" id="light-style" />

    <!-- CSS generated by mix -->
    <link href="{{asset('assets/admin/css/app.css')}}" rel="stylesheet">

</head>

<body class="loading" data-layout="detached"
    data-layout-config='{"layoutBoxed":false, "leftSidebarCondensed":false, "leftSidebarScrollable":false,"darkMode":false, "showRightSidebarOnStart": true}'>
    <div id="app">
        <home-app>

        </home-app>
    </div>

    <!-- javascript -->
    <!-- Generated by mix -->
    <script src="{{asset('assets/admin/js/app.js')}}"></script>

    <!-- bundle -->
    <script src="{{asset('assets/admin/js/vendor.min.js')}}"></script>
    <script src="{{asset('assets/admin/js/app.min.js')}}"></script>

</body>

</html>
