<!DOCTYPE html>
<html lang="en">


<head>
    <meta charset="utf-8" />
    <title>Tripavie - The trip of your life</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Venue and Retreat Booking - Tripavie" />
    <meta name="keywords" content="Travel, Yoga, Venue, Retreat" />
    <meta name="author" content="DepressedPsychiatrist" />
    <meta name="email" content="info@tripavie.com" />
    <meta name="website" content="https://tripavie.com/" />
    <!-- favicon -->
    <link rel="shortcut icon" href="{{ asset('favicon.png') }}">
    <!-- Bootstrap -->
    <link href="{{ asset('assets/user/frontend/css/bootstrap.min.css') }}" rel="stylesheet" type="text/css" />
    <!-- Icons -->
    <link href="{{ asset('assets/user/frontend/css/materialdesignicons.min.css') }}" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="{{ asset('assets/user/frontend/css/line.css') }}">
    <!-- Slider -->
    <link rel="stylesheet" href="{{ asset('assets/user/frontend/css/tiny-slider.css') }}" />
    <!-- tobii css -->
    <link href="{{ asset('assets/user/frontend/css/tobii.min.css') }}" rel="stylesheet" type="text/css" />
    <!-- Date picker -->
    <link rel="stylesheet" href="{{ asset('assets/user/frontend/css/datepicker.min.css') }}">
    {{-- Simple Bar --}}
    <link href="{{ asset('assets/user/frontend/css/simplebar.css') }}" rel="stylesheet" type="text/css" />
    <!-- Main Css -->
    <link href="{{ asset('assets/user/frontend/css/style.min.css') }}" rel="stylesheet" type="text/css"
        id="theme-opt" />
    <link href="https://fonts.cdnfonts.com/css/gilroy-bold?styles=20876,20877,20878,20879,20880" rel="stylesheet">
    <!-- CSS generated by mix  -->
    <link rel="stylesheet" href="{{ asset('assets/user/frontend/css/app.css') }}" />
</head>

<body data-bs-spy="scroll" data-bs-target=".navbar" data-bs-offset="300">
    <div id="app">
        <home-app>

        </home-app>
    </div>

    <!-- JS file generated by mix -->
    <script src="{{ asset('assets/user/frontend/js/mix/app.js') }}"></script>
    <!-- javascript -->
    <script src="{{ asset('assets/user/frontend/js/bootstrap.bundle.min.js') }}"></script>
    <!-- SLIDER -->
    <script src="{{ asset('assets/user/frontend/js/tiny-slider.js') }}"></script>
    <!-- simplebar -->
    <script src="{{ asset('assets/user/frontend/js/simplebar.min.js') }}"></script>
    <!-- Icons -->
    <script src="{{ asset('assets/user/frontend/js/feather.min.js') }}"></script>
    {{-- Shuffle and Tobii --}}
    <script src="{{ asset('assets/user/frontend/js/shuffle.min.js') }}"></script>
    <script src="{{ asset('assets/user/frontend/js/tobii.min.js') }}"></script>
    <!-- Main Js -->
    <script src="{{ asset('assets/user/frontend/js/plugins.init.js') }}"></script>
    <!--Note: All init js like tiny slider, counter, countdown, maintenance, lightbox, gallery, swiper slider, aos animation etc.-->
    <!-- initially called app.js, renamed to main.js because app.js will be generated by mix -->
    <script src="{{ asset('assets/user/frontend/js/main.js') }}"></script>
    <!--Note: All important javascript like page loader, menu, sticky menu, menu-toggler, one page menu etc. -->
</body>

</html>
